# Name of workflow
name: PHP CI

# Trigger the workflow on push on push for the master branch 
on:
  push:
    branches:      
       - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.2
        env:
          DB_CONNECTION: pgsql
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD:
          POSTGRES_DB: test
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
        # Step's name
      - name: Setup project
        run: make setup

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: make test       
        